export enum TwitchVideoStatuses {
  "IDLE" = "IDLE",
  "PREPARE_VIDEOS_PROGRESS" = "PREPARE_VIDEOS_PROGRESS",
  "PREPARE_VIDEOS_SUCCESS" = "PREPARE_VIDEOS_SUCCESS",
  "PREPARE_VIDEOS_ERROR" = "PREPARE_VIDEOS_ERROR",
  "RENDER_PROCESS" = "RENDER_PROCESS",
  "RENDER_SUCCESS" = "RENDER_SUCCESS",
  "RENDER_ERROR" = "RENDER_ERROR",
  "UPLOAD_PROGRESS" = "UPLOAD_PROGRESS",
  "UPLOAD_SUCCESS" = "UPLOAD_SUCCESS",
  "UPLOAD_ERROR" = "UPLOAD_ERROR",
}