version: '3.4'
services:
  web:
    container_name: content_manager_web
    build:
      context: ../../
      dockerfile: docker/prod/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../../:/app
  mysql:
    container_name: content_manager_db
    restart: always
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - my-datavolume:/var/lib/mysql
    ports:
    - "3308:3306"
  redis:
    container_name: content_manager_redis
    image: redis:alpine
    restart: always
    ports:
     - 6379:6379    
volumes:
  my-datavolume: