export enum TwitchVideoStatuses {
  "IDLE",
  "HANDLE_PROGRESS",
  "HANDLE_SUCCESS",
  "HANDLE_ERROR",
  "RENDER_PROCESS",
  "RENDER_SUCCESS",
  "RENDER_ERROR",
  "UPLOAD_PROGRESS",
  "UPLOAD_SUCCESS",
  "UPLOAD_ERROR"
}